name: kino_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.25.4
  cloud_firestore: ^4.15.4
  flutter_bloc: ^8.1.3
  flutter_screenutil: ^5.9.0
  freezed: ^2.4.7
  freezed_annotation: ^2.4.1
  auto_route: ^7.8.4
  get_it: ^7.6.7
  sqflite: ^2.3.2
  path_provider: ^2.1.2
  internet_connection_checker: ^1.0.0+1
  connectivity_plus: ^5.0.2
  eticon_api: ^2.0.5
  uuid: ^4.3.2
  get_storage: ^2.1.1
  intl: ^0.18.1
  youtube_player_flutter: ^8.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  auto_route_generator: ^7.3.2

flutter:
  uses-material-design: true

  fonts:
    - family: SFProText
      fonts:
        - asset: assets/fonts/SFProText-Regular.otf
          weight: 400